logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/webapp/*.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: time
      time_format: "YYYY-MM-DDTHH:mm:ss.SSSZZ"
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor]
