name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v20.6.1
        uses: actions/setup-node@v2
        with:
          node-version: "20.6.1"

      - name: Install Dependencies
        run: npm install

      - name: Run Hello World
        run: echo "Hello World"
