name: Packer CI

on:
  pull_request:
    branches:
      - main  

jobs:
  packer-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -fsSL https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip -o packer.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/
          packer version

      - name: Initialize Packer
        run: packer init .
        
      - name: Format Packer template
        run: packer fmt -check

      - name: Validate Packer template
        run: packer validate custom_image.pkr.hcl
