name: Workflow CI
 
on:
  pull_request:
    # types: [closed]
    branches:
      - main

jobs:
  build:
    name: test-build
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
         
    strategy:
      matrix:
        node-version: [20.x]
 
    steps:
 
      - name: Start MySQL
        run: |

          sudo systemctl start mysql
          sudo systemctl status mysql

      - name: Configure MySQL
        run: |
         sudo mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB }};"
         sudo mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "CREATE USER IF NOT EXISTS '${{ secrets.DB_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';"
         sudo mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "GRANT ALL PRIVILEGES ON ${{ secrets.DB }}.* TO '${{ secrets.DB_USER }}'@'localhost';"
         sudo mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "FLUSH PRIVILEGES;"

      - uses: actions/checkout@v2
 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Set up environment variables
        run: |         
          echo "DB_USER=${{ secrets.DB_USER}}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB=${{ secrets.DB }}" >> .env
          echo "HOST=${{ secrets.HOST }}" >> .env
          echo "DIALECT=${{ secrets.DIALECT }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "TOPIC_NAME=${{ secrets.TOPIC_NAME }}" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Start the application
        run: |
            npm start &
        
      - name: Wait for the application to be ready
        run: |
            sleep 10
            until curl -s http://localhost:8080; do
              sleep 5
            done

      - name: Run Tests
        run: npm test
      
      - name: Delete .env file
        run: rm .env

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
  
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
        
      - name: Create webapp.zip
        run: |
            zip -r webapp.zip ./

      # - name: Install Packer
      #   run: |
      #     curl -fsSL https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip -o packer.zip
      #     unzip packer.zip -d /tmp
      #     sudo mv /tmp/packer /usr/bin/packer
      #     packer --version

      - name: Initialize Packer
        run: packer init packer-config/custom_image.pkr.hcl

      - name: Format Packer template
        run: packer fmt -check packer-config/custom_image.pkr.hcl

      - name: Validate Packer template
        run: packer validate -var 'project_id=${{ secrets.GCP_PROJECT_ID }}' packer-config/custom_image.pkr.hcl
      

      # - name: Build custom image
      #   run:  packer build -var 'project_id=${{ secrets.GCP_PROJECT_ID }}'  packer-config/custom_image.pkr.hcl

      - name: Get Latest Image ID
        id: get_latest_image_id
        run: |
            IMAGE_ID=$(gcloud compute images list --filter="name=^${{ secrets.IMAGE_NAME_PREFIX }}-*" --sort-by="creationTimestamp desc" --format="value(ID)" | head -n 1)
            echo "::set-output name=image_id::$IMAGE_ID"
        
      # - name: Create new Instance Template version
      #   run: |
      #       gcloud compute instance-templates create new-webapp-instance-template 
      #       --source-image=${{ steps.get_latest_image_id.outputs.image_id }}
      #       --metadata=SQL_DB_USER=${{ secrets.SQL_DB_USER }},SQL_DB_PASSWORD=${{ secrets.SQL_DB_PASSWORD }},SQL_HOST=${{ secrets.SQL_HOST }}
      
      - name: Create new Instance Template version
        run: |
            # gcloud compute instance-templates create new-webapp-instance-template \
            #   --source-instance=${{ steps.get_latest_image_id.outputs.image_id }} \
            #   --metadata=SQL_DB_USER=${{ secrets.SQL_DB_USER }},SQL_DB_PASSWORD=${{ secrets.SQL_DB_PASSWORD }},SQL_HOST=${{ secrets.SQL_HOST }}
           
           
            # gcloud compute instance-templates create new-webapp-instance-template \
            # --description="${{ secrets.WEBAPP_TEMPLATE_DESCRIPTION }}" \
            # --machine-type=${{ secrets.MACHINE_TYPE }} \
            # --region=${{ secrets.REGION }} \
 
            # --disk=source-instance=${{ steps.get_latest_image_id.outputs.image_id }},size=${{ secrets.DISK_SIZE }},type=${{ secrets.DISK_TYPE }},auto-delete=true,boot=true \
            # --source-image-encryption-key ksm_key_self_link=${{ secrets.KMS_KEY_SELF_LINK }}
            # --network-interface=network=${{ secrets.VPC_NETWORK }},subnetwork=${{ secrets.WEBAPP_SUBNET }},access-config \
            # --service-account=${{ secrets.EMAIL }} \
            # --scopes=${{ secrets.SCOPES }} \
            # --tags=${{ secrets.TARGET_TAGS_HTTP }} \
            # --metadata=SQL_DB_USER=${{ secrets.SQL_DB_USER }},SQL_DB_PASSWORD=${{ secrets.SQL_DB_PASSWORD }},SQL_HOST=${{ secrets.SQL_HOST }},SQL_DB=${{ secrets.SQL_DB }},SQL_DIALECT=${{ secrets.SQL_DIALECT }},SQL_TOPIC_NAME=${{ secrets.SQL_TOPIC_NAME }},SQL_LOGPATH=${{ secrets.SQL_LOGPATH }} \

            gcloud compute instance-templates create new-webapp-instance-template \
            --description="${{ secrets.WEBAPP_TEMPLATE_DESCRIPTION }}" \
            --machine-type=${{ secrets.MACHINE_TYPE }} \
            --region=${{ secrets.REGION }} \
            --disk=name=source-image,boot=yes,auto-delete=yes \
            --source-image=${{ steps.get_latest_image_id.outputs.image_id }} \
            --source-image-encryption-key=ksm_key_self_link=${{ secrets.KMS_KEY_SELF_LINK }} \
            --network-interface=network=${{ secrets.VPC_NETWORK }},subnetwork=${{ secrets.WEBAPP_SUBNET }} \
            --service-account=${{ secrets.EMAIL }} \
            --scopes=${{ secrets.SCOPES }} \
            --tags=${{ secrets.TARGET_TAGS_HTTP }} \
            --metadata=SQL_DB_USER=${{ secrets.SQL_DB_USER }},SQL_DB_PASSWORD=${{ secrets.SQL_DB_PASSWORD }},SQL_HOST=${{ secrets.SQL_HOST }},SQL_DB=${{ secrets.SQL_DB }},SQL_DIALECT=${{ secrets.SQL_DIALECT }},SQL_TOPIC_NAME=${{ secrets.SQL_TOPIC_NAME }},SQL_LOGPATH=${{ secrets.SQL_LOGPATH }}

      - name: Update Managed Instance Group with new template
        run: | 
          gcloud compute instance-groups managed set-instance-template webapp_instance_group_manager --template=new-webapp-instance-template

      # - name: Recreate instances in Managed Instance Group
      #   run: |
      #     gcloud compute instance-groups managed recreate-instances webapp_instance_group_manager
      - name: Start rolling update for Managed Instance Group
        run: |
          gcloud compute instance-groups managed rolling-action start-update webapp_instance_group_manager --version template=new-webapp-instance-template

      # - name: Wait for Managed Instance Group refresh to complete
      #   run: |
      #     gcloud compute instance-groups managed wait-until webapp_instance_group_manager --zone=us-east1 --stable
      
      - name: Wait for Managed Instance Group refresh to complete
        run: |
          while true; do
            status=$(gcloud compute instance-groups managed describe webapp_instance_group_manager --zone=us-east1 --format=json | jq -r '.versionTarget.isReached')
            if [ "$status" = "true" ]; then
              break
            fi
            sleep 10
          done